# Generated by Django 3.2.4 on 2021-06-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='macota',
        ),
        migrations.AddField(
            model_name='animal',
            name='id_mascota',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
