# Generated by Django 3.2.4 on 2021-07-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
