# Generated by Django 3.2.4 on 2021-07-07 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
